version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/app/src
      - ./node_modules/@prisma/client:/app/node_modules/@prisma/client
      - /app/node_modules/
    ports:
      - ${PORT}:${PORT}
    command: npm run docker:start:dev
    env_file:
      - .env
    networks:
      - nest_services
    depends_on:
      - postgresql_service

  db:
    build:
      context: .
      dockerfile: Dockerfile-postgresql
    container_name: postgresql_service
    restart: on-failure
    networks:
      - nest_services
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  nest_services:
volumes:
  pg-data:
    driver: local

